name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew fatJar

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Zip lambda file
        run: zip -j deployment.zip build/libs/lambda-app-1.0.0.jar

      - name: Upload to S3
        run: aws s3 cp deployment.zip s3://stock-lambda-bucket/lambda-deployment/deployment.zip

      - name: Update Lambda function
        run: aws lambda update-function-code --function-name SaveStockData --s3-bucket stock-lambda-bucket --s3-key lambda-deployment/deployment.zip

